#pragma once
// 함수 원형 
void CppBasic();
void DefineFunction();
void Variable();
void Arithmatic();
void Increment();
void CompareFunction();
void Logical();
void IffunctionDesc();
void IffunctionEx01();
void IffunctionEx02();
void IffunctionEx03();
void IfNestDesc();
void IfNestEx01();
void IfNestEx02();
void SwitchEx();
void ForFunctionDesc();
void ForFunctionEx01();
void ForFunctionEx02();
void ForFunctionEx03();
void ForFunctionEx04();
void WhileFunctionDesc();
void WhileFunctionEx01();
void ParameterFunction(int param1, int param2);
int ReturnFunction();
int ParamReturn(int param1, int param2);
void Sum();
void PrintArray();
void SumAarry();
void Grade(int NumTest);
void ProcessScore();
void StringArray();
void BubbleSort();
void MultiArray();
void DefineStructure();
void StructureArray();
void Eunmeration();
void EvenOdd();
void PrintEven();
